FROM openjdk:17-jdk-slim-buster

ARG NOTE_APP_NAME
ARG NOTE_APP_VERSION

ENV NOTE_APP_NAME  ${NOTE_APP_NAME}
ENV NOTE_APP_VERSION ${NOTE_APP_VERSION}

WORKDIR /app

COPY ../../build/libs/$NOTE_APP_NAME-$NOTE_APP_VERSION.jar /app

ENTRYPOINT java -jar /app/$NOTE_APP_NAME-$NOTE_APP_VERSION.jar
